language: php

php:
  - 7.2
  - 7.3

env:
  - LARAVEL='^5.8'
  - LARAVEL='^6.0'
  - COMPOSER_FLAGS='--prefer-lowest'
  - COMPOSER_FLAGS='--prefer-stable'

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update
  - travis_retry composer require --no-update --no-interaction "illuminate/support:${LARAVEL}"

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction --prefer-dist --no-suggest

script: ./vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
